// Mock data for event testing and UI development

import { EventResponse } from './event-types';

export const mockEvents: EventResponse[] = [
  {
    id: 1,
    author_id: 'user_1',
    post_id: 101,
    title: 'Tech Innovation Summit 2025',
    description: 'Join us for a day of cutting-edge technology discussions, networking, and hands-on workshops with industry leaders.',
    location: 'Silicon Valley Convention Center',
    startDate: '2025-12-15',
    endDate: '2025-12-15',
    startTime: '09:00',
    endTime: '18:00',
    eventType: 'offline',
    category: 'Technology',
    capacity: 500,
    registrationRequired: true,
    tags: ['technology', 'innovation', 'networking'],
    created_at: '2025-11-01T10:00:00Z',
    attendees_count: 234,
    is_registered: false,
  },
  {
    id: 2,
    author_id: 'user_2',
    post_id: 102,
    title: 'Web Development Masterclass',
    description: 'Learn modern web development practices from expert developers. Covers React, TypeScript, and full-stack development.',
    location: 'Zoom Meeting',
    startDate: '2025-12-20',
    endDate: '2025-12-22',
    startTime: '14:00',
    endTime: '17:00',
    eventType: 'online',
    category: 'Education',
    capacity: 100,
    registrationRequired: true,
    tags: ['web-development', 'react', 'typescript'],
    created_at: '2025-11-05T14:30:00Z',
    attendees_count: 87,
    is_registered: true,
  },
  {
    id: 3,
    author_id: 'user_3',
    post_id: 103,
    title: 'Startup Networking Mixer',
    description: 'Connect with fellow entrepreneurs, investors, and industry professionals in a casual networking environment.',
    location: 'Downtown Coworking Space + Virtual Room',
    startDate: '2025-11-25',
    endDate: '2025-11-25',
    startTime: '18:00',
    endTime: '21:00',
    eventType: 'hybrid',
    category: 'Networking',
    registrationRequired: false,
    tags: ['startup', 'networking', 'business'],
    created_at: '2025-11-10T09:00:00Z',
    attendees_count: 45,
    is_registered: false,
  },
];
