/*
  # Create user saved YurService resources table

  1. New Tables
    - `user_saved_yurservice`
      - `id` (bigint, primary key, auto-increment)
      - `user_id` (uuid, references auth.users)
      - `resource_id` (integer, resource ID from app_yurservice_list)
      - `created_at` (timestamptz, default now())
  
  2. Security
    - Enable RLS on `user_saved_yurservice` table
    - Add policy for authenticated users to read their own saved resources
    - Add policy for authenticated users to insert their own saved resources
    - Add policy for authenticated users to delete their own saved resources
  
  3. Indexes
    - Index on user_id for faster lookups
    - Index on resource_id for faster joins
    - Unique constraint on (user_id, resource_id) to prevent duplicates
*/

CREATE TABLE IF NOT EXISTS user_saved_yurservice (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  resource_id integer NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  UNIQUE(user_id, resource_id)
);

CREATE INDEX IF NOT EXISTS idx_user_saved_yurservice_user_id ON user_saved_yurservice(user_id);
CREATE INDEX IF NOT EXISTS idx_user_saved_yurservice_resource_id ON user_saved_yurservice(resource_id);

ALTER TABLE user_saved_yurservice ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own saved resources"
  ON user_saved_yurservice FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can save resources"
  ON user_saved_yurservice FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can unsave resources"
  ON user_saved_yurservice FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);