// Mock network data with multi-level connections for testing network visualization

import { NetworkData, NetworkNode, NetworkEdge, NetworkStats, ConnectionType } from '../types/network';

export const CURRENT_USER_ID = 'timur-kakokho';

export const MOCK_NETWORK_NODES: NetworkNode[] = [
  {
    id: 'timur-kakokho',
    name: 'Тимур Какохо',
    username: 'timur-kakokho',
    about: 'IT юрист | Эксперт по цифровому праву',
    avatarUrl: null,
    role: 'IT-юрист',
    company: 'Независимый консультант',
    level: 1,
    connectionType: [],
    communities: ['IT', 'IT-юристы', 'ТК РФ'],
    isCurrentUser: true,
  },
  {
    id: 'ruslan-galiullin',
    name: 'Руслан Галиуллин',
    username: 'ruslan-galiullin',
    about: 'Юрист | Специалист по корпоративному праву',
    avatarUrl: null,
    role: 'Юрист',
    company: null,
    level: 1,
    connectionType: ['direct', 'following'],
    communities: ['Автоюристы'],
  },
  {
    id: 'daniil-petrov',
    name: 'Даниил Петров',
    username: 'daniil-petrov',
    about: 'Backend разработчик | Python, Django',
    avatarUrl: null,
    role: 'Backend Developer',
    company: 'Tech Solutions',
    level: 1,
    connectionType: ['direct', 'colleague'],
    communities: ['IT', 'Клуб Инкотермс'],
  },
  {
    id: 'imeni-plevalko',
    name: 'Имени Плевалко',
    username: 'imeni-plevalko',
    about: 'Адвокат | Специалист по делам бизнеса',
    avatarUrl: null,
    role: 'Адвокат',
    company: 'Юридическая фирма',
    level: 1,
    connectionType: ['direct', 'partner'],
    communities: ['IT'],
  },
  {
    id: 'danil-gubeydullin',
    name: 'Данил Губейдуллин',
    username: 'danil-gubeydullin',
    about: 'Адвокат | Трудовое право',
    avatarUrl: null,
    role: 'Адвокат',
    company: null,
    level: 1,
    connectionType: ['direct', 'community'],
    communities: ['ТК РФ'],
  },
  {
    id: 'marsel-mubarakzyanov',
    name: 'Марсель Мубаракзянов',
    username: 'marsel-mubarakzyanov',
    about: 'Адвокат | Уголовное право',
    avatarUrl: null,
    role: 'Адвокат',
    company: null,
    level: 1,
    connectionType: ['direct', 'follower'],
    communities: ['Клятва Гиппократа'],
  },
  {
    id: 'tk-rf-community',
    name: 'ТК РФ',
    username: 'tk-rf-community',
    about: 'Клуб юристов по трудовому праву',
    avatarUrl: null,
    role: 'Сообщество',
    company: null,
    level: 1,
    connectionType: ['community'],
    communities: ['ТК РФ'],
  },
  {
    id: 'inkoterms-club',
    name: 'Клуб Инкотермс',
    username: 'inkoterms-club',
    about: 'Клуб международных бизнес-практик',
    avatarUrl: null,
    role: 'Сообщество',
    company: null,
    level: 1,
    connectionType: ['community'],
    communities: ['Клуб Инкотермс'],
  },
  {
    id: 'hippocrat-oath',
    name: 'Клятва Гиппократа',
    username: 'hippocrat-oath',
    about: 'Клуб медицинских юристов',
    avatarUrl: null,
    role: 'Сообщество',
    company: null,
    level: 1,
    connectionType: ['community'],
    communities: ['Клятва Гиппократа'],
  },
  {
    id: 'it-lawyers',
    name: 'IT-юристы',
    username: 'it-lawyers',
    about: 'Сообщество юристов IT сферы',
    avatarUrl: null,
    role: 'Сообщество',
    company: null,
    level: 1,
    connectionType: ['community'],
    communities: ['IT-юристы'],
  },
  {
    id: 'section-127',
    name: '127-ФЗ',
    username: 'section-127',
    about: 'Клуб юристов по банкротству',
    avatarUrl: null,
    role: 'Сообщество',
    company: null,
    level: 1,
    connectionType: ['community'],
    communities: ['127-ФЗ'],
  },
  {
    id: 'auto-lawyers',
    name: 'Автоюристы',
    username: 'auto-lawyers',
    about: 'Сообщество автомобильных юристов',
    avatarUrl: null,
    role: 'Сообщество',
    company: null,
    level: 1,
    connectionType: ['community'],
    communities: ['Автоюристы'],
  },
  {
    id: 'elena-sokolova',
    name: 'Елена Соколова',
    username: 'elena-sokolova',
    about: 'UX/UI дизайнер | Специалист по пользовательскому опыту',
    avatarUrl: null,
    role: 'UX Designer',
    company: 'Design Studio',
    level: 2,
    connectionType: ['mutual'],
    communities: ['IT'],
  },
  {
    id: 'igor-volkov',
    name: 'Игорь Волков',
    username: 'igor-volkov',
    about: 'Frontend разработчик | React, TypeScript',
    avatarUrl: null,
    role: 'Frontend Developer',
    company: 'Web Agency',
    level: 2,
    connectionType: ['colleague'],
    communities: ['IT'],
  },
  {
    id: 'anna-mikhailova',
    name: 'Анна Михайлова',
    username: 'anna-mikhailova',
    about: 'Юрист по интеллектуальной собственности',
    avatarUrl: null,
    role: 'IP Lawyer',
    company: 'Patent Bureau',
    level: 2,
    connectionType: ['partner'],
    communities: ['IT-юристы'],
  },
  {
    id: 'sergey-novikov',
    name: 'Сергей Новиков',
    username: 'sergey-novikov',
    about: 'Системный аналитик | Big Data',
    avatarUrl: null,
    role: 'System Analyst',
    company: 'Data Corp',
    level: 2,
    connectionType: ['community'],
    communities: ['IT', 'Клуб Инкотермс'],
  },
  {
    id: 'maria-lebedeva',
    name: 'Мария Лебедева',
    username: 'maria-lebedeva',
    about: 'HR директор | Управление персоналом',
    avatarUrl: null,
    role: 'HR Director',
    company: 'Consulting Group',
    level: 2,
    connectionType: ['client'],
    communities: ['ТК РФ'],
  },
  {
    id: 'pavel-fedorov',
    name: 'Павел Фёдоров',
    username: 'pavel-fedorov',
    about: 'DevOps инженер | Kubernetes, Docker',
    avatarUrl: null,
    role: 'DevOps Engineer',
    company: 'Cloud Services',
    level: 2,
    connectionType: ['colleague'],
    communities: ['IT'],
  },
  {
    id: 'olga-romanova',
    name: 'Ольга Романова',
    username: 'olga-romanova',
    about: 'Бизнес-аналитик | Финансовый сектор',
    avatarUrl: null,
    role: 'Business Analyst',
    company: 'FinTech Inc',
    level: 2,
    connectionType: ['partner'],
    communities: ['Клуб Инкотермс'],
  },
  {
    id: 'dmitry-kozlov',
    name: 'Дмитрий Козлов',
    username: 'dmitry-kozlov',
    about: 'Product Manager | SaaS продукты',
    avatarUrl: null,
    role: 'Product Manager',
    company: 'SaaS Company',
    level: 2,
    connectionType: ['colleague'],
    communities: ['IT'],
  },
  {
    id: 'victoria-orlova',
    name: 'Виктория Орлова',
    username: 'victoria-orlova',
    about: 'Медицинский юрист | Здравоохранение',
    avatarUrl: null,
    role: 'Medical Lawyer',
    company: 'Health Law',
    level: 2,
    connectionType: ['community'],
    communities: ['Клятва Гиппократа'],
  },
  {
    id: 'alex-smirnov',
    name: 'Александр Смирнов',
    username: 'alex-smirnov',
    about: 'Арбитражный управляющий | Банкротство',
    avatarUrl: null,
    role: 'Арбитражный управляющий',
    company: null,
    level: 3,
    connectionType: [],
    communities: ['127-ФЗ'],
  },
  {
    id: 'natalia-volkova',
    name: 'Наталья Волкова',
    username: 'natalia-volkova',
    about: 'QA инженер | Автоматизация тестирования',
    avatarUrl: null,
    role: 'QA Engineer',
    company: 'Testing Lab',
    level: 3,
    connectionType: [],
    communities: ['IT'],
  },
  {
    id: 'andrey-petrov',
    name: 'Андрей Петров',
    username: 'andrey-petrov',
    about: 'Автоюрист | ДТП и страхование',
    avatarUrl: null,
    role: 'Автоюрист',
    company: null,
    level: 3,
    connectionType: [],
    communities: ['Автоюристы'],
  },
  {
    id: 'tatiana-ivanova',
    name: 'Татьяна Иванова',
    username: 'tatiana-ivanova',
    about: 'Специалист по международной торговле',
    avatarUrl: null,
    role: 'Trade Specialist',
    company: 'Import-Export Co',
    level: 3,
    connectionType: [],
    communities: ['Клуб Инкотермс'],
  },
  {
    id: 'maxim-kravtsov',
    name: 'Максим Кравцов',
    username: 'maxim-kravtsov',
    about: 'Fullstack разработчик | Node.js, React',
    avatarUrl: null,
    role: 'Fullstack Developer',
    company: 'Startup Hub',
    level: 3,
    connectionType: [],
    communities: ['IT'],
  },
];

export const MOCK_NETWORK_EDGES: NetworkEdge[] = [
  { source: 'timur-kakokho', target: 'ruslan-galiullin', connectionType: 'direct', relationship: 'Коллега', mutualConnections: 3 },
  { source: 'timur-kakokho', target: 'daniil-petrov', connectionType: 'colleague', relationship: 'Коллега по IT', mutualConnections: 5 },
  { source: 'timur-kakokho', target: 'imeni-plevalko', connectionType: 'partner', relationship: 'Деловой партнёр', mutualConnections: 2 },
  { source: 'timur-kakokho', target: 'danil-gubeydullin', connectionType: 'community', relationship: 'Через ТК РФ', mutualConnections: 1 },
  { source: 'timur-kakokho', target: 'marsel-mubarakzyanov', connectionType: 'direct', relationship: 'Знакомый', mutualConnections: 4 },
  { source: 'timur-kakokho', target: 'tk-rf-community', connectionType: 'community', relationship: 'Участник сообщества' },
  { source: 'timur-kakokho', target: 'inkoterms-club', connectionType: 'community', relationship: 'Участник клуба' },
  { source: 'timur-kakokho', target: 'hippocrat-oath', connectionType: 'community', relationship: 'Участник клуба' },
  { source: 'timur-kakokho', target: 'it-lawyers', connectionType: 'community', relationship: 'Участник сообщества' },

  { source: 'daniil-petrov', target: 'elena-sokolova', connectionType: 'colleague', relationship: 'Коллега', mutualConnections: 2 },
  { source: 'daniil-petrov', target: 'igor-volkov', connectionType: 'colleague', relationship: 'Коллега по проекту', mutualConnections: 3 },
  { source: 'daniil-petrov', target: 'inkoterms-club', connectionType: 'community', relationship: 'Участник клуба' },
  { source: 'daniil-petrov', target: 'pavel-fedorov', connectionType: 'colleague', relationship: 'Коллега', mutualConnections: 1 },

  { source: 'ruslan-galiullin', target: 'auto-lawyers', connectionType: 'community', relationship: 'Участник сообщества' },
  { source: 'ruslan-galiullin', target: 'maria-lebedeva', connectionType: 'client', relationship: 'Клиент', mutualConnections: 1 },

  { source: 'imeni-plevalko', target: 'anna-mikhailova', connectionType: 'partner', relationship: 'Партнёр', mutualConnections: 2 },
  { source: 'imeni-plevalko', target: 'it-lawyers', connectionType: 'community', relationship: 'Участник сообщества' },

  { source: 'danil-gubeydullin', target: 'tk-rf-community', connectionType: 'community', relationship: 'Активный участник' },
  { source: 'danil-gubeydullin', target: 'maria-lebedeva', connectionType: 'partner', relationship: 'Партнёр', mutualConnections: 1 },

  { source: 'marsel-mubarakzyanov', target: 'hippocrat-oath', connectionType: 'community', relationship: 'Участник клуба' },
  { source: 'marsel-mubarakzyanov', target: 'victoria-orlova', connectionType: 'community', relationship: 'Через клуб', mutualConnections: 1 },

  { source: 'elena-sokolova', target: 'igor-volkov', connectionType: 'colleague', relationship: 'Коллега по проекту', mutualConnections: 2 },
  { source: 'elena-sokolova', target: 'dmitry-kozlov', connectionType: 'colleague', relationship: 'Работали вместе', mutualConnections: 1 },

  { source: 'igor-volkov', target: 'pavel-fedorov', connectionType: 'colleague', relationship: 'Коллега', mutualConnections: 2 },
  { source: 'igor-volkov', target: 'natalia-volkova', connectionType: 'colleague', relationship: 'Коллега по команде' },

  { source: 'anna-mikhailova', target: 'it-lawyers', connectionType: 'community', relationship: 'Активный участник' },

  { source: 'sergey-novikov', target: 'inkoterms-club', connectionType: 'community', relationship: 'Участник клуба' },
  { source: 'sergey-novikov', target: 'olga-romanova', connectionType: 'partner', relationship: 'Партнёр по проектам' },
  { source: 'sergey-novikov', target: 'tatiana-ivanova', connectionType: 'community', relationship: 'Через клуб' },

  { source: 'maria-lebedeva', target: 'tk-rf-community', connectionType: 'community', relationship: 'Участник сообщества' },

  { source: 'pavel-fedorov', target: 'natalia-volkova', connectionType: 'colleague', relationship: 'Коллега' },
  { source: 'pavel-fedorov', target: 'maxim-kravtsov', connectionType: 'colleague', relationship: 'Бывший коллега' },

  { source: 'olga-romanova', target: 'inkoterms-club', connectionType: 'community', relationship: 'Участник клуба' },
  { source: 'olga-romanova', target: 'tatiana-ivanova', connectionType: 'partner', relationship: 'Партнёр' },

  { source: 'dmitry-kozlov', target: 'maxim-kravtsov', connectionType: 'colleague', relationship: 'Коллега' },

  { source: 'victoria-orlova', target: 'hippocrat-oath', connectionType: 'community', relationship: 'Администратор клуба' },

  { source: 'auto-lawyers', target: 'andrey-petrov', connectionType: 'community', relationship: 'Участник сообщества' },

  { source: 'section-127', target: 'alex-smirnov', connectionType: 'community', relationship: 'Участник сообщества' },

  { source: 'inkoterms-club', target: 'tatiana-ivanova', connectionType: 'community', relationship: 'Участник клуба' },
];

export const MOCK_NETWORK_DATA: NetworkData = {
  nodes: MOCK_NETWORK_NODES,
  edges: MOCK_NETWORK_EDGES,
};

export const MOCK_NETWORK_STATS: NetworkStats = {
  totalConnections: 25,
  directConnections: 6,
  followers: 12,
  following: 15,
  mutualConnections: 8,
  communities: 7,
  newThisMonth: 4,
  connectionsByType: {
    direct: 6,
    following: 1,
    follower: 1,
    community: 7,
    mutual: 8,
    colleague: 5,
    client: 2,
    partner: 3,
  },
  topCommunities: [
    { name: 'IT', count: 8 },
    { name: 'IT-юристы', count: 3 },
    { name: 'Клуб Инкотермс', count: 5 },
    { name: 'ТК РФ', count: 3 },
    { name: 'Клятва Гиппократа', count: 3 },
  ],
};

export const ALL_COMMUNITIES = [
  'IT',
  'IT-юристы',
  'ТК РФ',
  'Клуб Инкотермс',
  'Клятва Гиппократа',
  '127-ФЗ',
  'Автоюристы',
];
